[package]
name = "relic-of-lies-zk"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
contract = "0x0"

[dev-dependencies]

[dev-addresses]
